reqbeg/accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns = [ 
url(r'^signup/$', views.signuppage , name = 'signuppage'),
url(r'^login/$',views.loginpage, name = 'loginpage'),
url(r'^logout/$',views.logoutpage, name = 'logoutpage'),

]

reqbeg/accounts/models.py
from django.db import models

# Create your models here.

reqbeg/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
def signuppage(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request,user)
			return redirect('persons:abf')
	else:		
		form = UserCreationForm()
	return render(request, 'accounts/signup.html', {'form':form})
def loginpage(request):
	if request.method == 'POST':
		form = AuthenticationForm(data = request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request,user)
			return redirect('persons:abf')
	else:
		form = AuthenticationForm()
		return render(request,'accounts/login.html', {'form':form})	
# Create your views here.
def logoutpage(request):
	logout(request)
	return redirect('persons:abf')

reqbeg/accounts/templates/accounts/login.html
{%load static %}
<html >
<head>
 
  <title></title>

  <link rel="stylesheet"  href="{% static 'backgroung.css'%}">
</head>

<body>
	<nav>
		<ul>
			<li>
				<form class="logout-link" action="{% url 'accounts:logoutpage' %}" method="post">
					{% csrf_token %}
					<button type="submit"> logout </button>
				</form>
			</li>
		</ul>
	</nav>
	<h1>signup</h1> 
	 <form class="site-form" action="{%url 'accounts:loginpage'%}" method="post">
	 	{% csrf_token%}
	 {{form}}
	 <input type="submit" value= "login">
	 </form>
	
</body>

</html>

reqbeg/accounts/templates/accounts/signup.html
{%load static %}
<html >
<head>
 
  <title></title>

  <link rel="stylesheet"  href="{% static 'backgroung.css'%}">
</head>

<body>
	<nav>
		<ul>
			<li>
				<form class="logout-link" action="{% url 'accounts:logoutpage' %}" method="post">
					{% csrf_token %}
					<button type="submit"> logout </button>
				</form>
			</li>
		</ul>
	</nav>
	<h1>signup</h1>
	 <form class="site-form" action="/accounts/signup/" method="post">
	 	{% csrf_token%}
	 {{form}}
	 <input type="submit" value= "Signup">
	 </form>
	
</body>

</html>