reqbeg/person/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name ='persons'
urlpatterns = [
    url(r'^$', views.leaders, name = 'abf' ),
    url(r'^(?P<slug>[\w]+)/$', views.abc, name = 'hello'),

]

reqbeg/person/models.py
from django.conf import settings
from django.db import models

class Person(models.Model):
	
	name = models.CharField(max_length=30)
	about = models.TextField()
	slug = models.SlugField(max_length=30)
	photo = models.ImageField(default = 'default.png', blank = True)
	def __str__(self):
		return self.name
	def snippet(self):
		return (self.about[:20] + "...")

reqbeg/person/views.py
from django.shortcuts import render
from .models import Person
from django.http import HttpResponse
def leaders(request):
	List = Person.objects.all().order_by('name')
	return render(request,'person/person_list.html',{'list':List})	
#def person_details(request):
#	return render(request, 'person/person_details.html')
# Create your views here.of_people
def abc(request,slug):
	
	p = Person.objects.get(slug = slug)
	return render(request, 'person/person_details.html',{'person': p})

reqbeg/person/templates/person/homepage.html
<html >
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <link rel="stylesheet" href="css/styles.css?v=1.0">
  <meta "Hello there">
</head>

<body>
	This site does something.
  <script src="js/scripts.js"></script>
</body>
</html>

reqbeg/person/templates/person/person_details.html
{%load static %}
<html >
<head>
 
  <title>The story of {{person.name}}</title>

  <link rel="stylesheet"  href="{% static 'backgroung.css'%}">
</head>

<body>
	<nav>
		<ul>
			<li>
				<form class="logout-link" action="{% url 'accounts:logoutpage' %}" method="post">
					{% csrf_token %}
					<button type="submit"> logout </button>
				</form>
			</li>
		</ul>
	</nav>
	<div class="Person">
		<img src="{{person.photo.url}}"/>
		<h2> {{person.name}}</h2>
		<h3> {{person.about}}</h3>
		</div>
</body>

</html>

reqbeg/person/templates/person/person_list.html
{%load static %}
<html >
<head>
 
  <title>This site will many purposes, one of which will be write ups</title>

  <link rel="stylesheet"  href="{% static 'backgroung.css'%}">
</head>

<body>
	<nav>
		<ul>
			<li>
				<form class="logout-link" action="{% url 'accounts:logoutpage' %}" method="post">
					{% csrf_token %}
					<button type="submit"> logout </button>
				</form>
			</li>
		</ul>
	</nav>
	
	<div class="Person">
		{%for guy in  list %}
		<h2><a href="{% url 'persons:hello' slug=guy.slug %} ">{{guy.name}}</a> 
			
				<h3>{{guy.snippet}} </h3>

			 </h2>
		{% endfor %}	
		</div>
</body>

</html>